{
 "title": "Monitoring",
 "tags": [
  "cadvisor",
  "docker"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "host",
    "label": "Host",
    "query": {
     "query": "label_values({__name__=~\"container.*\"},instance)"
    }
   },
   {
    "name": "container",
    "label": "Container",
    "query": {
     "query": "label_values({__name__=~\"container.*\", instance=~\"$host\"},name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job='node_exporter',mode='idle'}[2m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage [%]",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "(node_memory_MemTotal_bytes{job='node_exporter'} - node_memory_MemFree_bytes{job='node_exporter'}) / node_memory_MemTotal_bytes{job='node_exporter'} * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "System Temperature",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{job='node_exporter'}",
     "legendFormat": "{{instance}} - {{sensor}}"
    }
   ]
  },
  {
   "title": "Free Space [GB]",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes{job='node_exporter',fstype!~'tmpfs|squashfs'} / 1024 / 1024 / 1024",
     "legendFormat": "{{instance}} - {{device}}"
    }
   ]
  },
  {
   "title": "I/O [KB/s]",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 8, "y": 15 },
   "targets": [
    {
     "expr": "sum(irate(node_disk_read_bytes_total{job='node_exporter'}[2m])) by (instance) / 1024",
     "legendFormat": "Read - {{instance}}"
    },
    {
     "expr": "sum(irate(node_disk_written_bytes_total{job='node_exporter'}[2m])) by (instance) / 1024",
     "legendFormat": "Write - {{instance}}"
    }
   ]
  },
  {
   "title": "Network Usage [KB/s]",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 15 },
   "targets": [
    {
     "expr": "sum(irate(node_network_transmit_bytes_total{job='node_exporter'}[2m])) by (instance) / 1024",
     "legendFormat": "Upload - {{instance}}"
    },
    {
     "expr": "sum(irate(node_network_receive_bytes_total{job='node_exporter'}[2m])) by (instance) / 1024",
     "legendFormat": "Download - {{instance}}"
    }
   ]
  },
  {
   "title": "Containers Info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "(time() - container_start_time_seconds{instance=~\"$host\",name=~\"$container\",name=~\".+\"})/86400",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}