global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['192.168.1.53:9100', '192.168.1.54:9100', '192.168.1.55:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: '$1'
        regex: "(.*):9100"
      - source_labels: [instance]
        regex: '192.168.1.53'
        target_label: instance
        replacement: 'rpi4-skynet'
      - source_labels: [instance]
        regex: '192.168.1.54'
        target_label: instance
        replacement: 'rpi3-stormwind'
      - source_labels: [instance]
        regex: '192.168.1.55'
        target_label: instance
        replacement: 'rpi3-jarvis'
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['192.168.1.53:8080', '192.168.1.54:8080', '192.168.1.55:8080']