version: '3'
services:
  pihole:
    container_name: skynet-pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    environment:
      TZ: 'Europe/London'  
      WEBPASSWORD: '[PIHOLE_PASSWORD]'
    volumes:
       - './etc-pihole/:/etc/pihole/'
       - './etc-dnsmasq.d/:/etc/dnsmasq.d/'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

  pihole-exporter:
    image: ekofr/pihole-exporter:latest
    container_name: skynet-pihole-exporter
    environment:
      - PIHOLE_HOSTNAME=[PIHOLE_HOSTNAME]
      - PIHOLE_PASSWORD=[PIHOLE_PASSWORD]
      - PORT=9617
    ports:
      - "9617:9617"